CAR-17: Add support for asserting JSONs equality in tests
mironuk/CarServiceWeb pull request #12
Opened 2019-01-11 15:09 UTC by majagabajaga

- Added support for loading JSONs as JsonElement from resources
- Added Asserting of equality of JSONs
- Added UTF-8 as default encoding
- Added commons-io as dependencies

2019-01-14 00:23 UTC, mironuk requested changes

2019-01-14 00:23 UTC, mironuk commented on .gitattributes
> +*.txt	eof=lf
There shoud be new line after last line.

2019-01-14 00:23 UTC, mironuk commented on src/test/java/carservice/test/AssertExt.java
> +        JsonReader expectedJsonReader = new JsonReader(r1);
Seems like these two lines can be moved to common method also.

2019-01-14 00:23 UTC, mironuk commented on src/test/java/carservice/test/testdata/f1.json
> +    "cat": "Barseeq"
Show stopper error: "Barseeq" should be "Barseek". Just kidding. :)

2019-01-14 00:23 UTC, mironuk commented on src/test/java/carservice/test/AssertExtTest.java
> +        String json1 = "{ \"meow\": \"meow\" }";
I think there should be string examples from f1.json and f2.json (full json with shuffled fields)

2019-01-15 05:26 UTC, majagabajaga commented on .gitattributes
> +*.txt	eof=lf
Added the new line character.

2019-01-15 05:27 UTC, majagabajaga commented on src/test/java/carservice/test/AssertExt.java
> +        JsonReader expectedJsonReader = new JsonReader(r1);
Done.

2019-01-15 05:27 UTC, majagabajaga commented on src/test/java/carservice/test/testdata/f1.json
> +    "cat": "Barseeq"
Donen't.

2019-01-15 05:27 UTC, majagabajaga commented on src/test/java/carservice/test/AssertExtTest.java
> +        String json1 = "{ \"meow\": \"meow\" }";
Done.

2019-01-15 05:54 UTC, merged